Laboratorio4/Laboratorio4/Models/PlanetaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Laboratorio4.Models
{
    public class PlanetaModel
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Es necesario que le indique el nombre del planeta")]
        [Display(Name = "Ingrese el nombre del planeta")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Es necesario que le indique el tipo del planeta")]
        [Display(Name = "Seleccione el tipo de planeta")]
        public string tipo { get; set; }

        [Required(ErrorMessage = "Es necesario que ingrese el numero de anillos")]
        [Display(Name = "Ingrese el numero de anillos del planeta")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Debe ingresar numeros")]
        public int numeroAnillos { get; set; }

        [Required(ErrorMessage = "Debe agregar un archivo (imagen, pdf, etc...)")]
        [Display(Name = "Ingrese el archivo con los detalles del planeta;")]
        public HttpPostedFileBase archivo { get; set; }

        public string tipoArchivo { get; set; }
    }
}

Laboratorio4/Laboratorio4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            ViewBag.ValorParaTest = 1;
            return View("Contact");
        }
    }
}

Laboratorio4/Laboratorio4/Controllers/PlanetasController.cs
using Laboratorio4.Handlers;
using Laboratorio4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio4.Controllers
{
    public class PlanetasController : Controller
    {
        // GET: Planetas

        public PlanetasHandler accesoDatos { get; set; }

        public PlanetasController()
        {
            accesoDatos = new PlanetasHandler();
        }

        public PlanetasController(PlanetasHandler planetasHandler)
        {
            accesoDatos = planetasHandler;
        }

        public ActionResult listadoDePlanetas()
        {
            PlanetasHandler accesoDatos = new PlanetasHandler();
            ViewBag.planetas = accesoDatos.obtenerTodoslosPlanetas();
            return View();
        }
        public ActionResult crearPlaneta()
        {
            return View("crearPlaneta");
        }

        [HttpPost]
        public ActionResult crearPlaneta(PlanetaModel planeta)
        {
            ViewBag.ExitoAlCrear = false;
            try
            {
                if (ModelState.IsValid)
                {
                    PlanetasHandler accesoDatos = new PlanetasHandler();
                    ViewBag.ExitoAlCrear = accesoDatos.crearPlaneta(planeta);
                    if (ViewBag.ExitoAlCrear)
                    {
                        ViewBag.Message = "El planeta " + planeta.nombre + "fue creado con exito! owo";
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.Message = "Algo salio mal y no fue posible crear el planeta unu";
                    }
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salio mal y no fue posible crear el planeta unu";
                return View();
            }
        }

        [HttpGet]
        public ActionResult editarPlaneta(int? identificador)
        {
            ActionResult vista;
            try
            {
                PlanetasHandler accesoDatos = new PlanetasHandler();
                PlanetaModel planetaModificar = accesoDatos.obtenerTodoslosPlanetas().Find(smodel => smodel.id == identificador);
                if (planetaModificar == null)
                {
                    vista = RedirectToAction("listadoDePlanetas");
                }
                else
                {
                    vista = View(planetaModificar);
                }
            }
            catch
            {
                vista = RedirectToAction("listadoDePlanetas");
            }
            return vista;
        }

        [HttpPost]
        public ActionResult editarPlaneta(PlanetaModel planeta)
        {
            try
            {
                PlanetasHandler accesoDatos = new PlanetasHandler();
                accesoDatos.modificarPlaneta(planeta);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

Laboratorio4/Laboratorio4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Laboratorio4/Laboratorio4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Laboratorio4/Laboratorio4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Laboratorio4/Laboratorio4/Views/Planetas/crearPlaneta.cshtml
@model Laboratorio4.Models.PlanetaModel
@{ 
    ViewBag.Title = "Crear Planeta";
    List<SelectListItem> tiposPlanetas = new List<SelectListItem>()
    {
        new SelectListItem { Text = "Rocoso"}, new SelectListItem { Text = "Gaseoso"}, new SelectListItem { Text = "Enano"}
    };

    <html>
<head>

</head>
<body>
    @if (ViewBag.Message != null)
    {
        if (ViewBag.ExitoAlCrear)
        {
            <div class="alert-success"><h3>@ViewBag.Message</h3></div>
        }
        else
        {
            <div class="alert-danger">
                <h3> @ViewBag.Message</h3>
            </div>
        }
    }

    @using (Html.BeginForm("crearPlaneta", "Planetas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <h1>Formulario de creacion de planetas</h1>

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.nombre)
                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tipo)
                @Html.DropDownListFor(model => model.tipo, tiposPlanetas, "-Sin seleccion-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.archivo)
                @Html.TextBoxFor(model => model.archivo, new { type = "file", @class = "btn btn alert-info" })
                @Html.ValidationMessageFor(model => model.archivo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.numeroAnillos)
                @Html.TextBoxFor(model => model.numeroAnillos, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.numeroAnillos, "", new { @class = "text-danger" })
            </div>
               
            <input type="submit" class="btn btn-success" value="Crear"/>

        </div>
    }
</body>
@section Scripts{
        @Scripts.Render("~/bundles/jqueryval")
}
</html>
}

Laboratorio4/Laboratorio4/Views/Planetas/editarPlaneta.cshtml
@model Laboratorio4.Models.PlanetaModel
@{
    ViewBag.Title = "Crear Planeta";
    List<SelectListItem> tiposPlanetas = new List<SelectListItem>()
{
        new SelectListItem { Text = "Rocoso"}, new SelectListItem { Text = "Gaseoso"}, new SelectListItem { Text = "Enano"}
    };

<html>
<head>

</head>
<body>
    @if (ViewBag.Message != null)
    {
       
    }

    @using (Html.BeginForm("editarPlaneta", "Planetas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <h1>Formulario de edicion de planetas</h1>
        @Html.HiddenFor(model=>model.id)
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.nombre)
                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tipo)
                @Html.DropDownListFor(model => model.tipo, tiposPlanetas, "-Sin seleccion-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.archivo)
                @Html.TextBoxFor(model => model.archivo, new { type = "file", @class = "btn btn alert-info" })
                @Html.ValidationMessageFor(model => model.archivo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.numeroAnillos)
                @Html.TextBoxFor(model => model.numeroAnillos, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.numeroAnillos, "", new { @class = "text-danger" })
            </div>

            <input type="submit" class="btn btn-success" value="Aplicar Cambios" />

        </div>
    }
</body>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
</html>
}

Laboratorio4/Laboratorio4/Views/Planetas/listadoDePlanetas.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Listado De Planetas</title>
    <meta charset="utf-8" />
    <!--Esto es un comentario-->
    <!--en el head se coloca informacion que es para el navegador, scripts, css-->
</head>
<body>
    <!--aqui inicia el cuerpo de la pagina que se esta creando (la vista)-->
    <h1>Listado de planetas</h1>

    @foreach (var planeta in ViewBag.planetas)
            {
                <hr />
                <h4>
                    <strong> Ficha del planeta: </strong> @planeta.id </h4>
              
                <p>

                    Nombre: @planeta.nombre <br />
                    Tipo: @planeta.tipo <br />
                    Numero de anillos: @planeta.numeroAnillos <br />

                </p>
                @Html.ActionLink("Modificar informacion", "editarPlaneta", new { identificador = planeta.id }, new { @class = "btn btn alert-info",@onclick = "return confirm('Quiere modificar este planeta?');"
                    }
                )
        <hr />
            }











    <div class="seccion_9" id="s9">
        <input type="button" value="Volver al inicio" onclick="history.back()" /><hr />

    </div>




</body>
</html>

Laboratorio4/Laboratorio4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Planetas", "listadoDePlanetas", "Planetas")</li>
                    <li>@Html.ActionLink("CrearPlaneta", "crearPlaneta", "Planetas")</li>
                    <li>@Html.ActionLink("EditarPlaneta", "editarPlaneta", "Planetas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>